from pygame.colordict import THECOLORS
from typehints import RGBAOutput

LOGGING = False

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2
FPS = 60

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_SPEED = 500
SHIP_WIDTH_RATIO = 1.5

ASTEROID_KINDS = 3
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100

ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_DRIFT_ANGLE = 30

SHOT_RADIUS = 5

BG: RGBAOutput = THECOLORS["black"]
SHIP_COLOR: RGBAOutput = THECOLORS["white"]
ASTEROID_COLOR: RGBAOutput = THECOLORS["white"]
BULLET_COLOR: RGBAOutput = THECOLORS["white"]
