from pygame.colordict import THECOLORS
from typehints import RGBAOutput

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2
FPS = 60

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
WIDTH_RATIO = 1.5

BG: RGBAOutput = THECOLORS["black"]
SHIP_COLOR: RGBAOutput = THECOLORS["white"]
