from pygame.colordict import THECOLORS

LOGGING = False

SHIP_WRAP_AROUND = True
BULLET_WRAP_AROUND = True
ASTEROID_WRAP_AROUND = False

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2

FPS = 60
MILLIS_TO_SECONDS = 1000

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
SHIP_WIDTH_RATIO = 1.5

ASTEROID_KINDS = 3
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100

ASTEROID_MIN_SPLIT_ANGLE = 20
ASTEROID_MAX_SPLIT_ANGLE = 50

ASTEROID_DRIFT_ANGLE = 30
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_ACCEL = 1.2

SHOT_RADIUS = 5

BG = THECOLORS["black"]
SHIP_COLOR = THECOLORS["white"]
ASTEROID_COLOR = THECOLORS["white"]
BULLET_COLOR = THECOLORS["white"]
