[project]
name = "Asteroids"
version = "0.1.0"
description = "Boot.dev: Asteroid"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "pygame-ce>=2.5",
]

[tool.pyright]
typeCheckingMode = "recommended"
reportUnusedCallResult = "hint"
reportUnusedExpression = "hint"
reportDeprecated = "hint"
reportUnannotatedClassAttribute = "hint"

[tool.uv.workspace]
members = [
    "Asteroids",
]
