#:schema none

name = 'Asteroids'
version = '0.9.0'
author_name = 'GoToLoop'
license = 'Unlicense'
description = 'Boot.dev: Asteroids'
url = 'https://GitHub.com/GoToLoop/Boot.dev'

[project]
name = "Asteroids"
version = "0.9.0"
description = "Boot.dev: Asteroids"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "pygame-ce>=2.5",
]

[tool.pyright]
# extends = "../../pyproject.toml"
typeCheckingMode = "recommended"
reportUnusedCallResult = "hint"
reportUnusedExpression = "hint"
reportDeprecated = "hint"
reportUnannotatedClassAttribute = "hint"
